{
    "name": "Pip Installer",
    "summary": """Install The Library With In The Odoo Environment in easily, directly and better way""",
    "category": "Tools",
    "version": "17.0.1.0",
    "sequence": 2,
    "author": "Prefortune",
    "license": "LGPL-3",
    "website": "",
    "description": """Python Library Installer Using Pip3""",
    'pre_init_hook': 'pre_init_hook',
    "application": True,
    "installable": True,
    "auto_install": False,
}
